import { Product } from '@/types';

export const products: Product[] = [
  {
    id: 'prod-001',
    slug: 'mcg-grad-hoodie',
    name: 'MCG Grad Hoodie',
    price: 79.99,
    category: 'Wearables',
    description: 'Celebrate your graduation in ultimate comfort. This premium heavyweight hoodie features the MCG crest embroidered on the chest, with "Class of 2025" detailing on the sleeve. Built for the moments that matter most.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Charcoal', 'Orange', 'Navy'],
    featured: true,
    gradCollection: true,
  },
  {
    id: 'prod-002',
    slug: 'mcg-classic-tee',
    name: 'MCG Classic Tee — Class of 2025',
    price: 34.99,
    category: 'Wearables',
    description: 'A timeless crew-neck tee that marks your achievement. Soft ring-spun cotton with the MCG shield printed front and center — because earning your credential deserves to be worn with pride.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Charcoal'],
    featured: true,
    gradCollection: true,
  },
  {
    id: 'prod-003',
    slug: 'mcg-scrubs',
    name: 'MCG Clinical Scrubs Set',
    price: 94.99,
    category: 'Clinical Wear',
    program: 'Healthcare',
    description: 'Professional-grade scrubs designed for MCG healthcare students and graduates. Moisture-wicking fabric, functional pockets, and tailored fit — ready for the clinic floor and beyond.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Teal', 'Navy', 'Charcoal'],
    badge: 'Healthcare',
    featured: true,
    gradCollection: false,
  },
  {
    id: 'prod-004',
    slug: 'mcg-diploma-frame',
    name: 'MCG Diploma Frame',
    price: 54.99,
    category: 'Keepsakes',
    description: 'Display your MCG diploma with the prestige it deserves. This museum-quality frame features double matting with the MCG crest foil-stamped in the lower mat. A keepsake built to last a lifetime.',
    sizes: ['One size'],
    colors: ['Black/Gold', 'Navy/Silver'],
    featured: true,
    gradCollection: true,
  },
  {
    id: 'prod-005',
    slug: 'mcg-tumbler',
    name: 'MCG Insulated Tumbler 750ml',
    price: 44.99,
    category: 'Accessories',
    description: 'Keep your drinks at the perfect temperature from morning lectures to evening study sessions. Double-wall vacuum insulated with the MCG shield laser-engraved — your daily companion on campus and beyond.',
    sizes: ['One size'],
    colors: ['Orange', 'Charcoal'],
    featured: true,
    gradCollection: false,
  },
  {
    id: 'prod-006',
    slug: 'mcg-grad-bundle',
    name: 'MCG Grad Bundle — Tee + Tumbler + Tote',
    price: 79.99,
    category: 'Bundles',
    description: 'The ultimate graduation gift set at an unbeatable value. Includes the MCG Classic Tee, Insulated Tumbler, and Embroidered Tote — everything a new graduate needs to carry their achievement forward.',
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
    gradCollection: true,
  },
  {
    id: 'prod-007',
    slug: 'mcg-tote',
    name: 'MCG Embroidered Tote Bag',
    price: 29.99,
    category: 'Accessories',
    description: 'A versatile canvas tote with the MCG shield elegantly embroidered. Perfect for textbooks, laptops, and everything in between. Durable enough for daily use, stylish enough to show your MCG pride anywhere.',
    sizes: ['One size'],
    colors: ['Natural', 'Navy'],
    featured: false,
    gradCollection: false,
  },
  {
    id: 'prod-008',
    slug: 'mcg-backpack',
    name: 'MCG Grad Backpack',
    price: 64.99,
    category: 'Accessories',
    description: 'Engineered for the graduate on the move. This structured backpack features a padded laptop compartment, water-resistant exterior, and the MCG shield embossed on the front panel. From campus to career, carry it all.',
    sizes: ['One size'],
    colors: ['Charcoal', 'Orange'],
    featured: false,
    gradCollection: true,
  },
];
